server:
  port: 80
  context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/booking?serverTimezone=UTC&amp;useUnicode=true&amp;characterEncoding=utf-8&useSSL=true
    username: root
    password: 9t37qmeOR64l
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update

  thymeleaf:
    cache: false

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

logging:
  level: debug
#  pattern:
#    console: "%d - %msg%n"
#  path: /log/tomcat/
#  file: /log/tomcat/project.log


