server:
  port: 8080
  context-path: /booking

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/booking?serverTimezone=UTC&amp;useUnicode=true&amp;characterEncoding=utf-8&useSSL=true
    username: root
    password: 9t37qmeOR64l
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: update

  thymeleaf:
    cache: false

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /log/tomcat/
#  file: /log/tomcat/project.log
#  level: debug
